### ISSUE TITLE
Ergebnis-Übersicht

### ISSUE THREAD

**Issue by commel** [Holarse-Linuxgaming/holarse-linux-spiele-grabber-and-sorting-machine-for-nerds#1]
Bitte eine Ergebnisübersicht (reicht eine Zeile) mit Spiele Gesamt steam/holarse, matches

**Comment by NoXPhasma** [comment]
Ist nun eingebaut, stellst du es dir so vor?

**Comment by NoXPhasma** [comment]
Achja, matches ist eher uninteressant, da dies bereits durch Holarse gedeckt ist. Es wird niemals mehr Holarse Einträge als Steam Einträge geben.

**Comment by commel** [comment]
Es ging nur darum, dass man eine der beiden Kennzahlen braucht, also entweder fehlende oder passende.

Sieht gut aus!
