### ISSUE TITLE
updateSteamdb() could avoid scraping, use local copy of GAMES.json instead

### ISSUE THREAD

**Issue by johndrinkwater** [Holarse-Linuxgaming/holarse-linux-spiele-grabber-and-sorting-machine-for-nerds#4]
Hey!
SteamDB hosts Linux game data sources on github, https://github.com/SteamDatabase/SteamLinux/ as an easily pars-able json file.
If you need to zip that data together with an appid to game name mapping, Valve provides http://api.steampowered.com/ISteamApps/GetAppList/v2 which is callable with an API key from here http://steamcommunity.com/dev/apikey (keep it private!)
More reference material http://wiki.teamfortress.com/wiki/WebAPI & https://partner.steamgames.com/

**Comment by NoXPhasma** [comment]
Thanks, I'll look into it.

**Comment by NoXPhasma** [comment]
@johndrinkwater the GAMES.json file only contains the games which are marked as working. I get only up to 10xx games out of it, while there are over 1200 games listed as Linux games on Steam.

With the current method I grab also the games from SteamDB which are not listed as working. Do you provide another json file which also contains the missing games?
